//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_Car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoPrijs
    {
        public System.DateTime StartDatum { get; set; }
        public Nullable<System.DateTime> EindDatum { get; set; }
        public decimal Prijs { get; set; }
        public int AutoTypeID { get; set; }
    
        public virtual AutoType AutoType { get; set; }
    }
}
