//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_Car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verhuring
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Verhuring()
        {
            this.Auto = new HashSet<Auto>();
        }
    
        public int ID { get; set; }
        public System.DateTime StartDatum { get; set; }
        public System.DateTime EindDatum { get; set; }
        public string GebruikerID { get; set; }
        public string Beschrijving { get; set; }
        public decimal Prijs { get; set; }
        public bool Geldig { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auto> Auto { get; set; }
    }
}
